# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outlook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlookkey',
            name='access_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='outlookkey',
            name='expires',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outlookkey',
            name='id_token',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='outlookkey',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
