# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='votes',
        ),
        migrations.AddField(
            model_name='stage',
            name='comment',
            field=models.TextField(default='no comment'),
            preserve_default=False,
        ),
    ]
