# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-04 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='date finished')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='stage',
            name='case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='name',
        ),
        migrations.RemoveField(
            model_name='case',
            name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='alert_date',
            field=models.DateTimeField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.AddField(
            model_name='alert',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Case'),
        ),
    ]
