# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 18:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_rule_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='file_id',
        ),
        migrations.AddField(
            model_name='case',
            name='case_id',
            field=models.CharField(default='#FFCDD2', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='color',
            field=models.CharField(default='#FFCDD2', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), help_text="eg:'1,3,5' will alert you 1/3/5 day before deadline", size=None),
        ),
    ]
